import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{AreaChart,Area,ResponsiveContainer,XAxis,YAxis,Tooltip,BarChart,Bar,PieChart,Pie}from"recharts";
import"./style.css";
const API="http://localhost:8000/api";
function App(){
const[watch,setWatch]=useState([]),[profiles,setProfiles]=useState([]),[ticker,setTicker]=useState("RELIANCE"),[profile,setProfile]=useState("hero"),[result,setResult]=useState(null),[loading,setLoading]=useState(false),[degraded,setDegraded]=useState(false),[tab,setTab]=useState("dashboard");
useEffect(()=>{fetch(API+"/watchlist").then(r=>r.json()).then(setWatch);fetch(API+"/profiles").then(r=>r.json()).then(setProfiles)},[]);
async function run(){setLoading(true);setResult(null);await new Promise(r=>setTimeout(r,700));try{let r=await fetch(API+"/recommendation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticker,profileId:profile,degraded})});setResult(await r.json())}catch(e){alert("Start backend first: uvicorn main:app --reload --port 8000")}setLoading(false)}
let chart=watch.map((x,i)=>({name:x.ticker,score:50+i*6+(x.change>0?14:0)}));
return <div className="app"><div className="web"></div>
<header><div className="brand"><span>🕷</span><div><b>SPIDER<span>WEB</span></b><small>AI FINANCIAL INTELLIGENCE NETWORK</small></div></div><nav>{["dashboard","agents","portfolio"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)}>{x.toUpperCase()}</button>)}</nav><div className="online">● SYSTEM ONLINE</div></header>
<main><section className="hero"><div><p className="eyebrow">HACKVERSE 2026 • PS-01</p><h1>Sense the market.<br/><em>Follow the web.</em></h1><p>A creative multi-agent intelligence system where independent agents spin a connected web of market signals, evidence and personalized investor decisions.</p><div className="badges"><span>⚡ 3 Parallel Agents</span><span>⌘ Explainable AI</span><span>◉ RAG Evidence</span></div></div><div className="radar"><i></i><i></i><div className="core">🕷<small>WEB<br/>CORE</small></div><b className="n n1">M</b><b className="n n2">V</b><b className="n n3">S</b></div></section>
<section className="controls"><div className="mission"><b>MISSION CONTROL</b><small>Configure your intelligence run</small></div><label>STOCK<select value={ticker} onChange={e=>setTicker(e.target.value)}>{watch.map(x=><option>{x.ticker}</option>)}</select></label><label>INVESTOR MODE<select value={profile} onChange={e=>setProfile(e.target.value)}>{profiles.map(x=><option value={x.id}>{x.name}</option>)}</select></label><label className="check"><input type="checkbox" checked={degraded} onChange={e=>setDegraded(e.target.checked)}/> TEST DATA OUTAGE</label><button onClick={run}>{loading?"SPINNING WEB...":"🕷 RUN INTELLIGENCE"}</button></section>
{tab==="dashboard"&&<><section className="stats"><div><small>ACTIVE AGENTS</small><b>03</b><span>All connected</span></div><div><small>WATCHLIST</small><b>{watch.length||6}</b><span>Stocks tracked</span></div><div><small>DOCUMENT WEB</small><b>12</b><span>Indexed sources</span></div><div><small>PIPELINE</small><b>LIVE</b><span>Parallel reasoning</span></div></section>
<section className="grid"><article className="card wide"><h3>MARKET WEB STRENGTH</h3><ResponsiveContainer width="100%" height={230}><AreaChart data={chart}><XAxis dataKey="name"/><YAxis/><Tooltip/><Area dataKey="score" stroke="#ff405a" fill="#e61f3d55" strokeWidth={3}/></AreaChart></ResponsiveContainer></article><article className="card"><h3>SECTOR WEB</h3><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={[{name:"Tech",value:35},{name:"Banking",value:25},{name:"Energy",value:20},{name:"FMCG",value:20}]} dataKey="value" nameKey="name" outerRadius={80}/><Tooltip/></PieChart></ResponsiveContainer></article></section>
<article className="card table"><h3>LIVE WATCHLIST</h3><div className="head"><span>STOCK</span><span>PRICE</span><span>MOVE</span><span>SECTOR</span><span>SIGNAL</span></div>{watch.map(x=><div className="row"><b>{x.ticker}</b><span>₹{x.price}</span><span className={x.change>=0?"up":"down"}>{x.change>=0?"+":""}{x.change}%</span><span>{x.sector}</span><span>{x.momentum}</span></div>)}</article></>}
{tab==="agents"&&<section className="page"><p className="eyebrow">MULTI-AGENT ORCHESTRATION</p><h2>Three specialists. One connected decision.</h2><div className="agents"><div>⚡<h3>Momentum Spider</h3><p>Tracks trend direction and movement velocity.</p></div><div>◉<h3>Volume Spider</h3><p>Checks whether participation confirms movement.</p></div><div>◌<h3>Sentiment Spider</h3><p>Uses retrieved documents and narrative context.</p></div></div><div className="pipeline">DATA → AGENTS → SYNTHESIS → PROFILE FILTER → DECISION</div></section>}
{tab==="portfolio"&&<section className="page"><p className="eyebrow">PORTFOLIO INTELLIGENCE</p><h2>Risk concentration radar</h2><div className="portfolio"><article className="card"><h3>RISK BUCKETS</h3><p>Technology <progress value="72" max="100"/></p><p>Banking <progress value="48" max="100"/></p><p>Energy <progress value="38" max="100"/></p></article><article className="card"><h3>PORTFOLIO ALERTS</h3><p>🕸 Diversification opportunity detected</p><p>⚡ Technology concentration above baseline</p><p>◉ No critical risk event detected</p></article></div></section>}
{result&&<section className="result"><p className="eyebrow">INTELLIGENCE COMPLETE</p><h2>Decision Web for {result.ticker}</h2><div className="resultgrid"><article className="card decision"><small>PERSONALIZED ACTION</small><div className="action">{result.action}</div><div className="conf"><b>{result.confidence}%</b><p>{result.summary}</p></div><div className="badges"><span>{result.profile.name}</span><span>Max {result.profile.maxAllocation}%</span>{result.degraded&&<span>Fallback active</span>}</div></article><article className="card trace"><h3>AGENT REASONING TRACE</h3>{result.trace.map(a=><div><i>{a.icon}</i><section><b>{a.agent}</b><p>{a.reason}</p></section><strong>{a.score}</strong><span>{a.signal}</span></div>)}</article><article className="card"><h3>RETRIEVED RAG EVIDENCE</h3><b>{result.source.title}</b><p>“{result.source.text}”</p><small>↳ {result.source.source}</small></article><article className="card"><h3>SESSION METRICS</h3><div className="metric"><b>{result.metrics.latencyMs}ms</b><b>{result.metrics.signalAccuracy30d}%</b><b>{result.metrics.webCoverage}%</b></div><ResponsiveContainer width="100%" height={130}><BarChart data={result.trace}><XAxis dataKey="agent" hide/><YAxis/><Tooltip/><Bar dataKey="score" fill="#e61f3d"/></BarChart></ResponsiveContainer></article></div></section>}
{!result&&tab==="dashboard"&&<div className="empty">🕸 Configure Mission Control and run the intelligence network to reveal the complete explainable reasoning chain.</div>}</main><footer>SPIDERWEB SIGNAL DESK • MULTI-AGENT EXPLAINABLE INTELLIGENCE • SYNTHETIC HACKATHON DATA • NOT FINANCIAL ADVICE</footer></div>}
createRoot(document.getElementById("root")).render(<App/>);
